package com.hetch.quizpaises;

import java.util.HashMap;
import java.util.Map;

public class CountriesDatabase {
    private static final String TAG = "CountriesDatabase";
    private Map<String, Integer> countries = new HashMap<>();

    public CountriesDatabase() {
        countries.put("Afeganistão", R.drawable.afghanistan);
        countries.put("Albânia", R.drawable.albania);
        countries.put("Argélia", R.drawable.algeria);
        countries.put("Samoa Americana", R.drawable.american_samoa);
        countries.put("Andorra", R.drawable.andorra);
        countries.put("Angola", R.drawable.angola);
        countries.put("Anguilla", R.drawable.anguilla);
        countries.put("Antígua e Barbuda", R.drawable.antigua_and_barbuda);
        countries.put("Argentina", R.drawable.argentina);
        countries.put("Armênia", R.drawable.armenia);
        countries.put("Aruba", R.drawable.aruba);
        countries.put("Austrália", R.drawable.australia);
        countries.put("Áustria", R.drawable.austria);
        countries.put("Azerbaijão", R.drawable.azerbaijan);
        countries.put("Bahamas", R.drawable.bahamas);
        countries.put("Bahrein", R.drawable.bahrain);
        countries.put("Bangladesh", R.drawable.bangladesh);
        countries.put("Barbados", R.drawable.barbados);
        countries.put("Bielorrússia", R.drawable.belarus);
        countries.put("Bélgica", R.drawable.belgium);
        countries.put("Belize", R.drawable.belize);
        countries.put("Benin", R.drawable.benin);
        countries.put("Bermudas", R.drawable.bermuda);
        countries.put("Butão", R.drawable.bhutan);
        countries.put("Bolívia", R.drawable.bolivia);
        countries.put("Bósnia e Herzegovina", R.drawable.bosnia);
        countries.put("Botsuana", R.drawable.botswana);
        countries.put("Brasil", R.drawable.brazil);
        countries.put("Ilhas Virgens Britânicas", R.drawable.british_virgin_islands);
        countries.put("Brunei", R.drawable.brunei);
        countries.put("Bulgária", R.drawable.bulgaria);
        countries.put("Burkina Faso", R.drawable.burkina_faso);
        countries.put("Burundi", R.drawable.burundi);
        countries.put("Cambodja", R.drawable.cambodia);
        countries.put("Camarões", R.drawable.cameroon);
        countries.put("Canadá", R.drawable.canada);
        countries.put("Cabo Verde", R.drawable.cape_verde);
        countries.put("Ilhas Cayman", R.drawable.cayman_islands);
        countries.put("República Centro-Africana", R.drawable.central_african_republic);
        countries.put("Chade", R.drawable.chad);
        countries.put("Chile", R.drawable.chile);
        countries.put("China", R.drawable.china);
        countries.put("Ilha Christmas", R.drawable.christmas_island);
        countries.put("Colômbia", R.drawable.colombia);
        countries.put("Comores", R.drawable.comoros);
        countries.put("Ilhas Cook", R.drawable.cook_islands);
        countries.put("Costa Rica", R.drawable.costa_rica);
        countries.put("Costa do Marfim", R.drawable.cote_d_ivoire);
        countries.put("Croácia", R.drawable.croatia);
        countries.put("Cuba", R.drawable.cuba);
        countries.put("Chipre", R.drawable.cyprus);
        countries.put("Norte do Chipre", R.drawable.cyprus_northern);
        countries.put("República Tcheca", R.drawable.czech_republic);
        countries.put("República Democrática do Congo", R.drawable.democratic_republic_of_the_congo);
        countries.put("Dinamarca", R.drawable.denmark);
        countries.put("Djibouti", R.drawable.djibouti);
        countries.put("Dominica", R.drawable.dominica);
        countries.put("República Dominicana", R.drawable.dominican_republic);
        countries.put("Equador", R.drawable.ecuador);
        countries.put("Egito", R.drawable.egypt);
        countries.put("El Salvador", R.drawable.el_salvador);
        countries.put("Guiné Equatorial", R.drawable.equatorial_guinea);
        countries.put("Eritreia", R.drawable.eritrea);
        countries.put("Estônia", R.drawable.estonia);
        countries.put("Etiópia", R.drawable.ethiopia);
        countries.put("Ilhas Malvinas", R.drawable.falkland_islands);
        countries.put("Ilhas Faroé", R.drawable.faroe_islands);
        countries.put("Fiji", R.drawable.fiji);
        countries.put("Finlândia", R.drawable.finland);
        countries.put("França", R.drawable.france);
        countries.put("Polinésia Francesa", R.drawable.french_polynesia);
        countries.put("Gabão", R.drawable.gabon);
        countries.put("Gâmbia", R.drawable.gambia);
        countries.put("Geórgia", R.drawable.georgia);
        countries.put("Alemanha", R.drawable.germany);
        countries.put("Gana", R.drawable.ghana);
        countries.put("Gibraltar", R.drawable.gibraltar);
        countries.put("Grécia", R.drawable.greece);
        countries.put("Groenlândia", R.drawable.greenland);
        countries.put("Granada", R.drawable.grenada);
        countries.put("Guam", R.drawable.guam);
        countries.put("Guatemala", R.drawable.guatemala);
        countries.put("Guiné", R.drawable.guinea);
        countries.put("Guiné Bissau", R.drawable.guinea_bissau);
        countries.put("Guiana", R.drawable.guyana);
        countries.put("Haiti", R.drawable.haiti);
        countries.put("Honduras", R.drawable.honduras);
        countries.put("Hong Kong", R.drawable.hong_kong);
        countries.put("Hungria", R.drawable.hungary);
        countries.put("Islândia", R.drawable.iceland);
        countries.put("Índia", R.drawable.india);
        countries.put("Indonésia", R.drawable.indonesia);
        countries.put("Irã", R.drawable.iran);
        countries.put("Iraque", R.drawable.iraq);
        countries.put("Irlanda", R.drawable.ireland);
        countries.put("Israel", R.drawable.israel);
        countries.put("Itália", R.drawable.italy);
        countries.put("Jamaica", R.drawable.jamaica);
        countries.put("Japão", R.drawable.japan);
        countries.put("Jordânia", R.drawable.jordan);
        countries.put("Cazaquistão", R.drawable.kazakhstan);
        countries.put("Quênia", R.drawable.kenya);
        countries.put("Quiribati", R.drawable.kiribati);
        countries.put("Kuwait", R.drawable.kuwait);
        countries.put("Quirguistão", R.drawable.kyrgyzstan);
        countries.put("Laos", R.drawable.laos);
        countries.put("Letônia", R.drawable.latvia);
        countries.put("Líbano", R.drawable.lebanon);
        countries.put("Lesoto", R.drawable.lesotho);
        countries.put("Libéria", R.drawable.liberia);
        countries.put("Líbia", R.drawable.libya);
        countries.put("Liechtenstein", R.drawable.liechtenstein);
        countries.put("Lituânia", R.drawable.lithuania);
        countries.put("Luxemburgo", R.drawable.lithuania);
        countries.put("Macau", R.drawable.macao);
        countries.put("Macedônia", R.drawable.macedonia);
        countries.put("Madagascar", R.drawable.madagascar);
        countries.put("Malawi", R.drawable.malawi);
        countries.put("Malásia", R.drawable.malaysia);
        countries.put("Maldivas", R.drawable.maldives);
        countries.put("Mali", R.drawable.mali);
        countries.put("Malta", R.drawable.malta);
        countries.put("Ilhas Marshall", R.drawable.marshall_islands);
        countries.put("Martinica", R.drawable.martinique);
        countries.put("Mauritânia", R.drawable.mauritania);
        countries.put("Ilhas Maurício", R.drawable.mauritius);
        countries.put("México", R.drawable.mexico);
        countries.put("Estados Federados da Micronésia", R.drawable.micronesia);
        countries.put("Moldávia", R.drawable.moldova);
        countries.put("Mônaco", R.drawable.monaco);
        countries.put("Mongólia", R.drawable.mongolia);
        countries.put("Montserrat", R.drawable.montserrat);
        countries.put("Marrocos", R.drawable.morocco);
        countries.put("Moçambique", R.drawable.mozambique);
        countries.put("Myanmar", R.drawable.myanmar);
        countries.put("Namíbia", R.drawable.namibia);
        countries.put("Nauru", R.drawable.nauru);
        countries.put("Nepal", R.drawable.nepal);
        countries.put("Países Baixos", R.drawable.netherlands);
        countries.put("Antilhas Neerlandesas ", R.drawable.netherlands_antilles);
        countries.put("Nova Zelândia", R.drawable.new_zealand);
        countries.put("Nicarágua", R.drawable.nicaragua);
        countries.put("Níger", R.drawable.niger);
        countries.put("Nigéria", R.drawable.nigeria);
        countries.put("Niue", R.drawable.niue);
        countries.put("Ilha Norfolk", R.drawable.norfolk_island);
        countries.put("Coréia do Norte", R.drawable.north_korea);
        countries.put("Noruega", R.drawable.norway);
        countries.put("Omã", R.drawable.oman);
        countries.put("Paquistão", R.drawable.pakistan);
        countries.put("Palau", R.drawable.palau);
        countries.put("Panamá", R.drawable.panama);
        countries.put("Papua Nova Guiné", R.drawable.papua_new_guinea);
        countries.put("Paraguai", R.drawable.paraguay);
        countries.put("Peru", R.drawable.peru);
        countries.put("Filipinas", R.drawable.philippines);
        countries.put("Ilhas Pitcairn", R.drawable.pitcairn_islands);
        countries.put("Polônia", R.drawable.poland);
        countries.put("Portugal", R.drawable.portugal);
        countries.put("Porto Rico", R.drawable.puerto_rico);
        countries.put("Catar", R.drawable.qatar);
        countries.put("Congo", R.drawable.republic_of_the_congo);
        countries.put("Romênia", R.drawable.romania);
        countries.put("Rússia", R.drawable.russian_federation);
        countries.put("Ruanda", R.drawable.rwanda);
        countries.put("São Cristóvão e Névis", R.drawable.saint_kitts_and_nevis);
        countries.put("Santa Lúcia", R.drawable.saint_lucia);
        countries.put("Saint-Pierre", R.drawable.saint_pierre);
        countries.put("São Vicente e Granadinas", R.drawable.saint_vicent_and_the_grenadines);
        countries.put("Samoa", R.drawable.samoa);
        countries.put("San Marino", R.drawable.san_marino);
        countries.put("São Tomé e Príncipe", R.drawable.sao_tome_and_principe);
        countries.put("Arábia Saudita", R.drawable.saudi_arabia);
        countries.put("Senegal", R.drawable.senegal);
        countries.put("Sérvia e Montenegro", R.drawable.serbia_and_montenegro);
        countries.put("Seychelles", R.drawable.seychelles);
        countries.put("Serra Leoa", R.drawable.sierra_leone);
        countries.put("Singapura", R.drawable.singapore);
        countries.put("Eslováquia", R.drawable.slovakia);
        countries.put("Eslovênia", R.drawable.slovenia);
        countries.put("Ilhas Salomão", R.drawable.soloman_islands);
        countries.put("Somália", R.drawable.somalia);
        countries.put("África do Sul", R.drawable.south_africa);
        countries.put("Geórgia do Sul", R.drawable.south_georgia);
        countries.put("Coréia do Sul", R.drawable.south_korea);
        countries.put("União Soviética", R.drawable.soviet_union);
        countries.put("Espanha", R.drawable.spain);
        countries.put("Sri Lanka", R.drawable.sri_lanka);
        countries.put("Sudão", R.drawable.sudan);
        countries.put("Suriname", R.drawable.suriname);
        countries.put("Suazilândia", R.drawable.swaziland);
        countries.put("Suécia", R.drawable.sweden);
        countries.put("Suíça", R.drawable.switzerland);
        countries.put("Síria", R.drawable.syria);
        countries.put("Taiwan", R.drawable.taiwan);
        countries.put("Tajiquistão", R.drawable.tajikistan);
        countries.put("Tanzânia", R.drawable.tanzania);
        countries.put("Tailândia", R.drawable.thailand);
        countries.put("Região Autônoma do Tibete", R.drawable.tibet);
        countries.put("Timor-Leste", R.drawable.timor_leste);
        countries.put("Togo", R.drawable.togo);
        countries.put("Tonga", R.drawable.tonga);
        countries.put("Trindade e Tobago", R.drawable.trinidad_and_tobago);
        countries.put("Tunísia", R.drawable.tunisia);
        countries.put("Turquia", R.drawable.turkey);
        countries.put("Torcomenistão", R.drawable.turkmenistan);
        countries.put("Turks e Caicos", R.drawable.turks_and_caicos_islands);
        countries.put("Tuvalu", R.drawable.tuvalu);
        countries.put("Emirados Árabes Unidos", R.drawable.uae);
        countries.put("Uganda", R.drawable.uganda);
        countries.put("Ucrânia", R.drawable.ukraine);
        countries.put("Inglaterra", R.drawable.united_kingdom);
        countries.put("Estados Unidos da América", R.drawable.united_states_of_america);
        countries.put("Uruguai", R.drawable.uruguay);
        countries.put("Ilhas Virgens Americanas", R.drawable.us_virgin_islands);
        countries.put("Uzbequstão", R.drawable.uzbekistan);
        countries.put("Vanuatu", R.drawable.vanuatu);
        countries.put("Vaticano", R.drawable.vatican_city);
        countries.put("Venezuela", R.drawable.venezuela);
        countries.put("Vietnã", R.drawable.vietnam);
        countries.put("Wallis e Futuna", R.drawable.wallis_and_futuna);
        countries.put("Iêmen", R.drawable.yemen);
        countries.put("Zâmbia", R.drawable.zambia);
        countries.put("Zimbábue", R.drawable.zimbabwe);
    }

    public Map<String, Integer> getCountries() {
        return countries;
    }
}
